server:
  port: 8080

spring:
  application:
    name: search-module
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}

module:
  catalog:
    url: ${CATALOG_MODULE_URL:http://localhost:8080}