server:
  port: 8080

spring:
  application:
    name: search-module
  elasticsearch:
    uris: https://my-elasticsearch-project-ab19d9.es.us-central1.gcp.elastic.cloud:443
    api-key: WU1BNTJKMEJnYWQ5VDNTdVR2UVI6akVuSklNTW5NLVRPWWo0SEZLWE9hUQ==

module:
  catalog:
    url: ${CATALOG_MODULE_URL:http://localhost:8080}