server:
  port: 8080

spring:
  application:
    name: cart-module
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ecommerce
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

module:
  catalog:
    url: ${CATALOG_MODULE_URL:http://localhost:8080}
  inventory:
    url: ${INVENTORY_MODULE_URL:http://localhost:8080}
  promotion:
    url: ${PROMOTION_MODULE_URL:http://localhost:8080}