server:
  port: 8080

spring:
  application:
    name: settlement-module
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ecommerce
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

module:
  order:
    url: ${ORDER_MODULE_URL:http://localhost:8080}