-- V13__add_audit_columns_to_all_tables.sql
-- Add audit columns (soft delete, version, timestamps) to all tables that miss them.

-- iam-module
ALTER TABLE roles ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE permissions ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE otp_tokens ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE otp_tokens ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE otp_tokens ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE otp_tokens ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE otp_tokens ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE otp_tokens ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- catalog-module
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE product_images ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE product_attributes ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE product_attributes ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE product_attributes ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE product_attributes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE product_attributes ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE product_attributes ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- inventory-module
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE stock_reservations ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE stock_reservations ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE stock_reservations ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE stock_reservations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE stock_reservations ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE stock_reservations ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- cart-module
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- order-module
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE order_timeline ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE order_timeline ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE order_timeline ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE order_timeline ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE order_timeline ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE order_timeline ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE return_requests ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE return_requests ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE return_requests ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE return_requests ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE return_requests ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE return_requests ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- payment-module
ALTER TABLE payment_transactions ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE payment_transactions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE payment_transactions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE payment_transactions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE payment_transactions ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE payment_transactions ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE refunds ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- promotion-module
ALTER TABLE coupon_usages ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE coupon_usages ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE coupon_usages ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE coupon_usages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE coupon_usages ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE coupon_usages ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- shipping-module
ALTER TABLE delivery_zones ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE delivery_zones ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE delivery_zones ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE delivery_zones ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE delivery_zones ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE delivery_zones ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE shipping_rates ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE shipping_rates ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE shipping_rates ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE shipping_rates ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE shipping_rates ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE shipping_rates ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- settlement-module
ALTER TABLE vendor_accounts ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE vendor_accounts ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE vendor_accounts ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE vendor_accounts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE vendor_accounts ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE vendor_accounts ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE commission_rules ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE commission_rules ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE commission_rules ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE commission_rules ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE commission_rules ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE commission_rules ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE settlement_items ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE settlement_items ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE settlement_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE settlement_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE settlement_items ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE settlement_items ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- cms-module
ALTER TABLE pages ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE pages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE pages ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE homepage_sections ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE homepage_sections ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE homepage_sections ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE homepage_sections ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE homepage_sections ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE homepage_sections ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE homepage_section_items ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE homepage_section_items ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE homepage_section_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE homepage_section_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE homepage_section_items ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE homepage_section_items ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE faqs ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE faqs ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE announcements ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- support-module
ALTER TABLE ticket_messages ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE ticket_messages ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE ticket_messages ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE ticket_messages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE ticket_messages ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE ticket_messages ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE disputes ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
